config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root to: "home#index"
  root to: 'user_stocks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  before_action :set_user_stock, only: [:show, :edit, :update, :destroy]

  # GET /user_stocks
  # GET /user_stocks.json
  def index
    @user_stocks = UserStock.all
  end

  # GET /user_stocks/1
  # GET /user_stocks/1.json
  def show
  end

  # GET /user_stocks/new
  def new
    @user_stock = UserStock.new
  end

  # GET /user_stocks/1/edit
  def edit
  end

  # POST /user_stocks
  # POST /user_stocks.json
  def create
    @user_stock = UserStock.new(user_stock_params)

    respond_to do |format|
      if @user_stock.save
        format.html { redirect_to @user_stock, notice: 'User stock was successfully created.' }
        format.json { render :show, status: :created, location: @user_stock }
      else
        format.html { render :new }
        format.json { render json: @user_stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_stocks/1
  # PATCH/PUT /user_stocks/1.json
  def update
    respond_to do |format|
      if @user_stock.update(user_stock_params)
        format.html { redirect_to @user_stock, notice: 'User stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_stock }
      else
        format.html { render :edit }
        format.json { render json: @user_stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_stocks/1
  # DELETE /user_stocks/1.json
  def destroy
    @user_stock.destroy
    respond_to do |format|
      format.html { redirect_to user_stocks_url, notice: 'User stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_stock
      @user_stock = UserStock.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_stock_params
      params.require(:user_stock).permit(:user_id, :stock_symbol, :quantity, :price, :purchased_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/views/home/index.html.erb
<h1>Hello world</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stocks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user_stocks/_form.html.erb
<%= form_with(model: user_stock, local: true) do |form| %>
  <% if user_stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_stock.errors.count, "error") %> prohibited this user_stock from being saved:</h2>

      <ul>
        <% user_stock.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :stock_symbol %>
    <%= form.text_field :stock_symbol %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :purchased_at %>
    <%= form.datetime_select :purchased_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_stocks/edit.html.erb
<h1>Editing User Stock</h1>

<%= render 'form', user_stock: @user_stock %>

<%= link_to 'Show', @user_stock %> |
<%= link_to 'Back', user_stocks_path %>

app/views/user_stocks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Stocks</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Stock symbol</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Purchased at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_stocks.each do |user_stock| %>
      <tr>
        <td><%= user_stock.user_id %></td>
        <td><%= user_stock.stock_symbol %></td>
        <td><%= user_stock.quantity %></td>
        <td><%= user_stock.price %></td>
        <td><%= user_stock.purchased_at %></td>
        <td><%= link_to 'Show', user_stock %></td>
        <td><%= link_to 'Edit', edit_user_stock_path(user_stock) %></td>
        <td><%= link_to 'Destroy', user_stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Stock', new_user_stock_path %>

app/views/user_stocks/new.html.erb
<h1>New User Stock</h1>

<%= render 'form', user_stock: @user_stock %>

<%= link_to 'Back', user_stocks_path %>

app/views/user_stocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_stock.user_id %>
</p>

<p>
  <strong>Stock symbol:</strong>
  <%= @user_stock.stock_symbol %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @user_stock.quantity %>
</p>

<p>
  <strong>Price:</strong>
  <%= @user_stock.price %>
</p>

<p>
  <strong>Purchased at:</strong>
  <%= @user_stock.purchased_at %>
</p>

<%= link_to 'Edit', edit_user_stock_path(@user_stock) %> |
<%= link_to 'Back', user_stocks_path %>